#!/usr/bin/ruby

Vagrant.configure("2") do |config|
    config.vm.box = "bttf"
    config.vm.box_url = "http://poke.vagrant.boxes.s3.amazonaws.com/ubuntu_precise64_blank.box"
    config.vm.host_name = "bttf"

    config.vm.network :forwarded_port, guest: 80, host: 8080
    config.vm.network :private_network, ip: "10.10.10.10"

    config.vm.provider :virtualbox do |v|
        v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
    end

    # The Project Mount - This Directory
    config.vm.synced_folder ".", "/home/vagrant/switchboard", :nfs => true

end
